### ISSUE TITLE
Missmatch between module numbers - eg 6 months visit Child Safety says 5 (does that means 5 months or visit number?) but visit number is 10

### ISSUE THREAD

**Issue by gosso22** [d-tree-org/opensrp-client-chw-kk#116]

**Comment by issyzac** [comment]
We have agreed to remove the numbers after the module name so that being visit number or month number because they will be confusing and since all the contents will be of the same "Number" it makes sense to have the visit number/Month number at the tio of the visit modules screen only once

Also the bango kitita numbers are recommended to have since they will help the CHWs refer to the corresponding bango kitita topic for a particular module so we will have to standardize that as well and I think I have added an item to standardize that
