### ISSUE TITLE
Update PNC Danger signs

### ISSUE THREAD

**Issue by issyzac** [d-tree-org/opensrp-client-chw-kk#126]
- [ ] Review translation: "kichwa kuuma / macho kutoona viuri"
- [ ] Mpauko/kupiga rangi
- [ ] Kuvuja kwa mkojo/ kutoka kwa mkojo

**Comment by devcolonel** [comment]
@issyzac 
the first one I checked on KK dictionary it reads the same but I think it must read **macho kutoona vizuri**
and the second one and the third one reads the same on the KK-dictionary.
so I think  for the third one **kutoka kwa mkojo** is perfect swahili instead of **kuvuja kwa mkojo**, and not sure about **kupiga rangi** I think he/she mean **Kupauka rangi**

**Comment by issyzac** [comment]
Can you comment the link to the data dictionary?
