### ISSUE TITLE
In Communication Assessment, there is a box that is in Swahili.     If I declare that the mother doesn’t communicate with the child the icon is still white and it should be green. Moreover, the app thinks that I didn’t anwer the module so doesn’t allow me to save my progress.

### ISSUE THREAD

**Issue by issyzac** [d-tree-org/opensrp-client-chw-kk#334]

**Comment by Zubakes** [comment]
@issyzac translation for box in swahili "Can you show me how you communicate with your baby? What do you think your child is learning while you communicate?"

**Comment by Zubakes** [comment]
@issyzac Swahili text box replaced with english text box test: Passed
Also, i think what Pallavi meant to say was yellow instead of green when she does not communicate with her child? Which is what we have now on the app after testing so: Passed.
Save progress: Passed
Although the visit box does not change to green showing visit complete on child profile. It is empty.

**Comment by issyzac** [comment]
Hi Grace, we can take a look at that as a different item, this ticket only focuses on communication assesment module fix
